#!/bin/bash
#PBS -P sb4 
#PBS -q express
#PBS -l walltime=5:00:00
#PBS -l mem=4gb
#PBS -l ncpus=32
#PBS -l wd

module load openmpi/1.8

mpirun /short/dh4/sat562/MyOctopus/octopus-4.1.1-MPI/BuildSystem/bin/octopus_mpi > output